# Reeranser  Deloppgave 3

::: {#refs}

::: Tanner, R. K., and C. J. Gore. 2012. Physiological Tests for Elite Athletes 2nd Edition. Book. Human Kinetics. https://books.google.no/books?id=0OPIiMks58MC

::: Hempel, Carl G.
(1966) Scientific Inquiry; Invention and Test.
\| C G Hempel, Philosophy of Natural Science (s.3-18) Princeton, Prentice Hall.

::: Godfrey-Smith, P. (2003) Bayesianism and modern theories of evidence.
\| P.

::: Godfrey-Smith, Theory and Reality: An Introduction to the Philosophy of Science (s. 202-218) Chicago; University of Chicaago Press.

::: Popper, K.
(1969) Conjectures and Refutations; The Growth of Scientific Knowledge (3. Utg) London: Routledge.

::: Bird, A.
(2021) The British Journal for the Philosophy of Science, vol.72, nr. 4 December 2021

::: Okasha S.
(2016) Philosophy of Science, a very short introduction.
(s. 1-70) second edition 2016, Oxford University press.

:::[1] Eur J Appl Physiol. 2003 Nov;90(5-6):505-13. doi: 10.1007/s00421-003-0889-0. Epub 2003 Jul 26.
Impact of menstrual cycle phase on the exercise status of young, sedentary women
Leanne M Redman 1, Garry C Scroop, Robert J Norman

:::[2] Kathmandu Univ Med J (KUMJ).  2012 Oct-Dec;10(40):25-9. doi: 10.3126/kumj.v10i4.10990.
Endurance capacity and cardiorespiratory responses in sedentary females during different phases of menstrual cycle
A Bandyopadhyay 1, R Dalui

:::[3] European Journal of applied Physiology,  July 7th 1994,
Effects of the menstrual cycle phase on the blood lactale responses to exercise.
m.McCracken, B. Ainsworth, A.C. Hackney

:::[4] J Physiol.  1996 May 15;493 ( Pt 1)(Pt 1):267-72. doi: 10.1113/jphysiol.1996.sp021381.
Changes in muscle strength, relaxation rate and fatiguability during the human menstrual cycle
R Sarwar 1, B B Niclos, O M Rutherford

:::[5] Clinical Trial J Physiol.  2001 Jan 1;530(Pt 1):161-6. doi: 10.1111/j.1469-7793.2001.0161m.x.
The influence of menstrual cycle phase on skeletal muscle contractile characteristics in humans
X A Janse de Jonge 1, C R Boot, J M Thom, P A Ruell, M W Thompson

:::[6] Browner, Newman: Designing clinical Research, 5th edition, Wolters Kluwer, ISBN-13.978-1-975174-40-8

:::[7] https://psyarxiv.com/p39sc/ QALMRI- method